function createfigure1(xdata1, ydata1, zdata1, X1, Y1)
%CREATEFIGURE1(XDATA1,YDATA1,ZDATA1,CDATA1,X1,Y1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Jun-2013 13:16:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0806451612903226 0.435714285714286 0.372503840245776 0.485714285714285],...
    'CLim',[0.7 1.1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 200]);
grid(axes1,'on');
hold(axes1,'all');

% Create mesh
mesh(xdata1,ydata1,zdata1,'Parent',axes1);
xlim([0 200]);
% Create xlabel
xlabel('X (mm)');

% Create colorbar
colorbar('peer',axes1);
% Resize the axes in order to prevent it from shrinking.
set(axes1,...
    'Position',[0.1 0.4 0.3 0.5]);

% Create axes
axes2 = axes('Parent',figure1,'XTick',zeros(1,0),...
    'Position',[0.6 0.1 0.3 0.4],...
    'FontSize',25);
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X1,Y1,'Parent',axes2,'MarkerSize',20,'Marker','.');

% Create axes
axes3 = axes('Parent',figure1,'YTick',[0 0.5],...
    'Position',[0.6 0.6 0.3 0.4],...
    'FontSize',25);
box(axes3,'on');
hold(axes3,'all');

% Create plot
plot(X1,X1,'Parent',axes3,'Marker','.');

% Create arrow
annotation(figure1,'arrow',[0.205069124423963 0.205837173579109],...
    [0.430616341030195 0.793960923623446],'HeadWidth',25,'HeadStyle','none',...
    'LineStyle','--',...
    'LineWidth',3);

