function startup
    Colors = ([228,26,28;...
        55,126,184;...
        77,175,74;...
        152,78,163;...
        255,127,0;...
        255,255,51;...
        166,86,40;...
        247,129,191;...
        153,153,153])./255;
    
    
    
    set(0,'DefaultFigureWindowStyle','docked');
    set(0,'DefaultAxesFontSize',12);
    set(0,'DefaultLineMarkerSize',8);
    
    set(groot, 'DefaultLineLineWidth', 2, ...
        'DefaultTextInterpreter', 'tex', ...
        'DefaultAxesTickLabelInterpreter', 'tex', ...
        'DefaultAxesFontName', 'Century Gothic', ...
        'DefaultLegendInterpreter', 'tex', ...
        'DefaultAxesLineWidth', 1, ...
        'DefaultAxesBox', 'on', ...
        'DefaultFigureInvertHardcopy', 'off', ...
        'DefaultAxesColorOrder', Colors);
