% test script - add data more than just phedi location to some DataStruct

%% define parameter structure
Param = struct(...
    'experNum',             1,...
    'eventNum',             3,...
    'lineNum',              'all',...
    'BlurROT',              20,...
    'UsrRes',               nan,...
    'numOOM',               3,...
    'phediRelative2first',  1,...
    'preRowsTime',          3e-3,...
    'postRowsTime',         3e-3,...
    'prePhediTime',         1.5e-4,...
    'postPhediTime',        3e-4,...
    'smooth4Phedi',         0.001,...
    'PhediSafetyDist',      30,...
    'QuickAndDirty',        0,...
    'scratchWidth',         100*1e-6,...
    'scratchRegionMeters',  [0.07 0.09],...
    'defPhotoLoc',          0.08,...
    'Cr',                   1255,...
    'CohsvModl_h',          1e-7...
    );

%% load and repair files
ExpNums = [3,5,6];
for i=ExpNums
    %-- load
    name=['allPhediStructures_Exp',num2str(i),'.mat'];
    DataStructWPhedis = load(name,'PhediStructCell');
    PhediStructCell = DataStructWPhedis.PhediStructCell;
    UpdatedPhediStructCell = cell(size(PhediStructCell));
    for j=1:length(PhediStructCell)
        try
            %-- add location
            DataStructWLocation = phedi_add_phediLocationVectors(PhediStructCell{j});
            %-- add velocity vectors
            DataStructWVelocity= phedi_add_velocity_to_struct(DataStructWLocation);
            %-- smooth functions measured
            DataStructWSmooth = phedi_addSmoothedFunctions2Struct(DataStructWVelocity);
            %-- add
            DataStructWSol = phedi_addLEFMandCohesive2Struct(DataStructWSmooth,Param);
            %-- add param
            DataStructWSol.Param = Param;
            %-- final struct
            UpdatedPhediStructCell{j} = DataStructWSol;
        catch
        end
    end
    saveName = ['PhediStructuresUpDt_Exp',num2str(i),'.mat'];
    save(saveName,'UpdatedPhediStructCell','-v7.3');
end


