function NewDataStruct = phedi_addSmoothedFunctions2Struct(DataStruct,varargin)
%phedi_addSmoothedFunctions2Struct will add to DataStruct (the output of 
% Movie_phedi_from_folder_2_data) the phedi location and velocity after
% smoothenong phediLocation by a known factor. 

%% set defaults
[Nsmt] = setDefaults4function(varargin,4);

%% get data from current structure
NewDataStruct = DataStruct;
PhediLocation = NewDataStruct.PhediData.PhediLocation;
timeVec = NewDataStruct.PhediData.timeVec;
firstFrame4Phedi = NewDataStruct.PhediData.firstFrame4Phedi;
lastFrame4Phedi = NewDataStruct.PhediData.lastFrame4Phedi;
center_of_mass = NewDataStruct.AsperityData.center_of_mass;
RowOverTime = NewDataStruct.AsperityData.RowOverTime;
phedisInitialLocsInPix = NewDataStruct.PhediData.phedisInitialLocsInPix;
PhediLocationPix = NewDataStruct.PhediData.PhediLocationPix;
timeCount = NewDataStruct.AsperityData.timeCount;
res = NewDataStruct.ExperimentData.res;
fps = NewDataStruct.CamMeta.FrameRate;
BigPicRotStruct = NewDataStruct.BigPicRotStruct;

%% backup original data
[PhediLocation_original, PhediVelocity_original, timeVec_4vel_original,...
    t_mins_t_tip_4vel_original,...
    x_mins_x_tip_4vel_original,Xc_original,PhotoLocation_original,...
    Cf_original...
    ] = deal(...
    PhediLocation,...
    DataStruct.PhediData.PhediVelocity,...
    DataStruct.PhediData.timeVec_4vel,...
    DataStruct.PhediData.t_mins_t_tip_4vel,...
    DataStruct.PhediData.x_mins_x_tip_4vel,...
    DataStruct.PhediData.Xc,...
    DataStruct.PhediData.PhotoLocation,...
    DataStruct.PhediData.Cf);

%% smooth phedi location 
PhediLocation = conv2(PhediLocation,ones(Nsmt,1)/Nsmt,'same');
PhediLocation([1:Nsmt,end-Nsmt:end],:) = nan;

%% phedi velocity
[PhediVelocity, timeVec_4vel] = phedi_calcVelocity(PhediLocation,timeVec);

%% phedi cohesive zone measurments
% t_tips = phedi_findFrontTimeFromLocation(PhediLocation,timeVec);
% [t_tips,Cf_pixPerSec] = phedi_findFrontTimeFromCenterOfMass...
%     (center_of_mass,timeVec,firstFrame4Phedi:lastFrame4Phedi,RowOverTime,phedisInitialLocsInPix);
% Cf_MetPerSec = Cf_pixPerSec/res;
[tFrontPassing_Frms , CfPixPerFrm]= phedi_findFrontTimeFrontSpeed(...
    RowOverTime,firstFrame4Phedi:lastFrame4Phedi,phedisInitialLocsInPix,PhediLocationPix);
t_tips = interp1(1:size(RowOverTime,1),timeCount,tFrontPassing_Frms);
Cf_MetPerSec = CfPixPerFrm*fps/res;
% [t_mins_t_tip_4vel, x_mins_x_tip_4vel, PhotoLocation] = phedi_velocityFromTime2Space(timeVec_4vel,BigPicRowOverTimeStruct,t_tips);
[t_mins_t_tip_4vel, x_mins_x_tip_4vel, PhotoLocation] = phedi_velocityFromTime2SpacePerVector(timeVec_4vel,BigPicRotStruct,t_tips,Cf_MetPerSec);
try 
    Xc = phedi_calcCohesiveZoneByVel(PhediVelocity,x_mins_x_tip_4vel);
catch
    Xc = nan;
end


%% update strcture
[NewDataStruct.PhediData.PhediLocation,...
    NewDataStruct.PhediData.PhediVelocity,...
    NewDataStruct.PhediData.timeVec_4vel,...
    NewDataStruct.PhediData.t_mins_t_tip_4vel,...
    NewDataStruct.PhediData.x_mins_x_tip_4vel,...
    NewDataStruct.PhediData.Xc,...
    NewDataStruct.PhediData.PhotoLocation,...
    NewDataStruct.PhediData.Nsmt,...
    NewDataStruct.PhediData.PhediVelocity_original,...
    NewDataStruct.PhediData.timeVec_4vel_original,...
    NewDataStruct.PhediData.t_mins_t_tip_4vel_original,...
    NewDataStruct.PhediData.x_mins_x_tip_4vel_original,...
    NewDataStruct.PhediData.Xc_original,...
    NewDataStruct.PhediData.PhotoLocation_original,...
    NewDataStruct.PhediData.Cf_MetPerSec_original,...
    NewDataStruct.PhediData.PhediLocation_original...
    ] = deal(...
    PhediLocation,...
    PhediVelocity, timeVec_4vel,t_mins_t_tip_4vel,x_mins_x_tip_4vel,...
    Xc,PhotoLocation,Nsmt,...
    PhediVelocity_original, timeVec_4vel_original,...
    t_mins_t_tip_4vel_original,x_mins_x_tip_4vel_original,Xc_original,...
    PhotoLocation_original,Cf_original,PhediLocation_original...
    );



end